# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            My title
tagline:          'A Jekyll site'
description:      'No one said anything about dependencies!'
# url:              https://fongandrew.github.io
# baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Brett Lee'

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true